# This file is a template, and might need editing before it works on your project.
# Official docker image.
#image: docker:latest
#
#services:
#  - eu.gcr.io/bredec-gitlab/bredec-ci:db25bdcd

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  GCR_PRJ: "bredec-pwa"
  STAGING_REGISTRY: "eu.gcr.io"

stages:
  - build-pwa-dev
  - deploy-pwa-dev
  - build-pwa-prod
  - deploy-pwa-prod

before_script:
  - echo $GITLAB_PWA_GAURAV > $HOME/.config/gcloud/bredec-pwa-35d611ae4ff8.json && gcloud auth activate-service-account --key-file=$HOME/.config/gcloud/bredec-pwa-35d611ae4ff8.json && export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.config/gcloud/bredec-pwa-35d611ae4ff8.json
 
build-pwa-dev:
  stage: build-pwa-dev
  image: eu.gcr.io/bredec-gitlab/bredec-ci:db25bdcd
  script:
    - tree -L 2 $CI_PROJECT_DIR
  only:
    - develop

deploy-pwa-dev:
  stage: deploy-pwa-prod
  image: eu.gcr.io/bredec-gitlab/bredec-ci:db25bdcd
  script:
    - tree -L 2 $CI_PROJECT_DIR
    - bash scripts/deploy.sh
  only:
    - develop

build-pwap-prod:
  stage: build-pwa-prod
  image: eu.gcr.io/bredec-gitlab/bredec-ci:db25bdcd
  script:
        - tree -L 2 $CI_PROJECT_DIR
  only:
    - master

deploy-pwa-prod:
  stage: deploy-pwa-prod
  image: eu.gcr.io/bredec-gitlab/bredec-ci:db25bdcd
  script:
    - tree -L 2 $CI_PROJECT_DIR
    - bash scripts/deploy.sh
  only:
    - master

    


